version: '3.9'
services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_db
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/nest_db?schema=public
      PORT: 3000
      FE_URL: http://localhost
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "80:80"
